"""Generated by Django 3.2.5 on 2021-07-28 11:28."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Миграция."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("siren", "Сирена"),
                            ("speaker", "Громкоговоритель"),
                        ],
                        max_length=10,
                        verbose_name="Тип устройста",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=255, verbose_name="Адрес"),
                ),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=6, max_digits=8, verbose_name="Широта"
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Долгота"
                    ),
                ),
                (
                    "radius",
                    models.PositiveIntegerField(
                        verbose_name="Радиус зоны звукопокрытия"
                    ),
                ),
            ],
            options={
                "verbose_name": "Устройство оповещения",
                "verbose_name_plural": "Устройства оповещения",
            },
        ),
    ]
